### ISSUE TITLE
Best place for a discussion

### ISSUE THREAD

**Issue by graphific** [samim23/GitXiv#1]
As a first start we though it might be worth trying to have discussions about GitXiv (whats great about it, what sucks, how might GitXiv best fit into the openscience world, etc) as github issues. We would love to hear your input.

Samim & Roelof

**Comment by 4fur4** [comment]
I miss some more CV categories like Image classification, object detection, image segmentation, captioning... Video related categories might be also necessary in the close future.

**Comment by samim23** [comment]
Great suggestion!

Currently "Image classification, object detection, image segmentation" are all summarised under "Computer Vision". Its a tricky balance to decide in which area to explode the namespace further. 

You can image, if we do every sub-cat for every research field, we will easily have 200 categories. Thats a little unrealistic to maintain unfortunately. 

Looking into alternatives like a additional Tag system. The nice thing about a fixes category schema, its the clarity/cleanses there of. The currently available full text search help as well and could be expanded to be a semantic search. 

Thoughts?

**Comment by 4fur4** [comment]
Pretty true. A Tag system sounds like a good alternative imo (apart from
the categories, of course).
