### ISSUE TITLE
expose "arXiv" link domain, if its to arXiv or somehwere else

### ISSUE THREAD

**Issue by silky** [samim23/GitXiv#11]
why is this? why is it titled arXiv if it doesn't go to the arXiv?

**Comment by graphific** [comment]
In a perfect world researchers would all submit their papers to arXiv, but as this is not always the case: the important thing is for the article to be "freely" available. Also for older papers, arXiv wasn't around yet :) 
Then there's also other variants of arXiv, ie for biology: biorxiv.org

**Comment by samim23** [comment]
I agree, its confusing at time. We are looking at options how to make this clearer. 
What do you think about this:

arXiv = Text
GitHub = Code

underneath we would always show the actual URL where the link goes to.
Comments?

**Comment by silky** [comment]
i think when someone submits a link they can just type in what the name is

maybe it could be a choice of "arXiv/.../other". 

i would really like to be able to differentiate those submissions that are actually related to arXiv papers.

**Comment by samim23** [comment]
We are investigating options here as described above. The "user can just type what ever they like" scenario is sub-optimal, as it means A) more mental work for the editor B) attack vector space for trolls. I agree with the problem you highlight though, it should be easier to see where links lead to.

**Comment by graphific** [comment]
yeh I agree its not optimal right now, maybe just expose the link itself, or domain it leads to: should be an easy enough fix.

**Comment by danstowell** [comment]
It's really unpleasant to click a link titled "arXiv" and to land somewhere else. It's also best if the user will know if they're clicking on a PDF link or a web link. I'd suggest that the system should detect if the link is to an arXiv paper, and if so: (a) re-generate the link as an `/abs` link so that the UX is consistent; (b) use "arXiv" for the title. Else if not an arXiv link, just call it "text" or whatever you like.

**Comment by samim23** [comment]
@danstowell your suggestion sounds great, we´ll investigate this in the next iteration.
