### ISSUE TITLE
There are too many categories

### ISSUE THREAD

**Issue by gasche** [samim23/GitXiv#14]
My browser cannot show the complete list of categories (unless I use keyboard keys to scroll, because reaching for the scrollbar would make the categories menu lose focus and disappear).

It seems clear that a more hierarchical model is needed, with sub-categories, or a tag model where people would only subscribe to a small number of tags to see on their main page.

I think that as a list of "root categories" it would be reasonable to use arXiv's classification of Computer Science: [CoRR Subject Areas](http://arxiv.org/corr/subjectclasses). However, that would be fairly different from the current set which focuses on machine learning (the community where GitXiv is most active right now).

**Comment by samim23** [comment]
Great point. Please read our thoughts on namespacing on the wiki: 
https://github.com/samim23/GitXiv/wiki/Thoughts-on-GitXiv

We would love to see people fork the project for further specialisation. e.g. bio.gitxiv.com .
Investigating a federated/distributed model might be very appropriate.

Thoughts?

**Comment by bobye** [comment]
Also, I would say current contents are overly occupied by deep learning (>50%, I guess). Adding some category filters (blacklist and whitelist) could be very useful.

**Comment by graphific** [comment]
@bobye yes this is mainly because atm for instance 90 out of the total 130 posts are about Deep Learning. As the CS topic space grows this will hopefully change, and also we will be in any case forced to use a more hierarchical topic mapping, like @gasche also proposes.
