### ISSUE TITLE
"Competition" will antagonize a part of the potential user base

### ISSUE THREAD

**Issue by gasche** [samim23/GitXiv#15]
I know that the machine learning community loves a good competition, but in other research areas "competition" is not a particularly positive word, and it may even put people off from participating to GitXiv. I understand that it is also one of the core ideas of the site, so it's perfectly fine if your answer to this issue is "sorry, we like it that way".

I think the idea of "we compete on whoever releases the code _first_" is silly (the first code is not the best code!). I think the idea of a collaboration to provide an implementation for an article is excellent, but it could simply be described this way, as a collaboration. Replacing the antagonizing word "competition" with "collaboration" throughout the [Competitions](http://gitxiv.com/page/competitions) webpage makes for a silly diagram, but otherwise gives a very good result -- I think it would be better than the current page in terms of not putting people off. You could simply remove point (3), and replace (4) by "the resulting implementation(s) are given exposure on GitXiv".

(Of course, there may be advantages in the wording of "competition", as it might help some people's motivation to produce implementation. My subjective guess is that the disadvantages are larger -- current research environments are rather perceived as _too competitive_ than not competitive enough for everyone's sake.)

**Comment by samim23** [comment]
Very good points! We thought this through along similar lines as your describing. 

Finally we opted to with "competition" + "silly diagram" as its the de facto standard in ML right now (kaggle). 

Generally speaking, its better to provide people with something familiar + 1 piece of new information - then something completely new, with a weak link to known territory. That said, lets have a debate here and hear what the community thinks of this. Ultimately, its our collective decision.

**Comment by graphific** [comment]
@gasche just edited the title of the issue to "Competition", at least thats what I thought to be the correct word.

Further, yes both Samim and I are actually totally into more collaboration:  us kicking of the GitXiv experiment is an example of that. For me the word "competition" is meant as both playful, and as an extra incentive for people to reach out and find fellow ML enthusiasts to implement a paper together.
In the first iteration I actually wanted to call it <i>compellaboration</i> or something along those lines, but I think that would have just made things more confusing.

On the [GitXiv competition page at Github](https://github.com/GitXiv/DeepQA) I've tried to clarify more about this. Short quote:
<pre>While this is a competition, GitXiv incentive collaboration: the person or team of persons who contributes the most to the final working implementation wins! This means that it might be awesome if someone fixes the final bug of an implementation in one line (ie a typo), but the person(s) spending weeks on coding things up might make a better chance of getting added to GitXiv's Hall of Fame. Or if someone has written an extremely detailed and useful blog post on the matter and added it here, he or she might be the grand final winner instead, who knows :)

<b>So if its all about who contributes the most, who decides on that, you?</b>
Excellent question! No in the end we will find a way to decide together, by voting, or by an open hangout discussion, or whatever...</pre>

So all in all, I think this is a very important discussion, worthwhile of having.

**Comment by HenryElder** [comment]
Competition really does seem like the wrong word for it. Given that the goal is to develop open solutions that the whole community can use. It's more participation than competition.

**Comment by VolutionLabs** [comment]
challenge?
