### ISSUE TITLE
Cannot link twitter account, user option: remove account

### ISSUE THREAD

**Issue by torinaki** [samim23/GitXiv#16]
I have already created account manualy. Now I want to link my twitter account, but there no such functionality.
Also I have tried to login with twitter, but instead to link twitter account with already existing one it creates new one. Now I can't even complite newly created account by twitter OAuth, because I get an error that email already taken.

**Comment by graphific** [comment]
@torinaki you should be able to add your twitter handle to your profile by going to the "Edit Account" option:
<img width="300" alt="edit account" src="https://cloud.githubusercontent.com/assets/10637696/9043148/a750b550-3a13-11e5-9843-05aa1faa8f14.png">

**Comment by graphific** [comment]
Dmitry I see you got 2 profiles, both with an empty "Twitter Username". Can you explain me what exactly doesnt work?

**Comment by torinaki** [comment]
@graphific thank you for quick response. My bad that I have missed that profile has twitter username field. But anyway it doesn't solve my problem. 
Yes, now I have two profiles. Reproduction steps is following:
1. Create profile manualy(do not specify twitter account login name in profile settings)
2. Logout and try to login with twitter

Actual result: new profile will be created and you will do not able to specify your email to complite registation because it already used
Expected resullt: twitter account must associated with existing account by email

**Comment by torinaki** [comment]
Here is error that I get after twitter login:
![image](https://cloud.githubusercontent.com/assets/1269372/9064963/af70fd0c-3ad7-11e5-823b-8a45debc3b46.png)

**Comment by graphific** [comment]
which of the 2 would you want deleted: torinaki or dmitry.balabka	?
which reminds me of an option to add: remove account

**Comment by torinaki** [comment]
Please delete account "torinaki".
Thanks you :)
On Вт, 4 авг. 2015 г. at 18:45 Roelof Pieters <notifications@github.com>
wrote:

> which of the 2 would you want deleted: torinaki or dmitry.balabka ?
> which reminds me of an option to add: remove account
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samim23/GitXiv/issues/16#issuecomment-127654781>.
>
-- 
Best Regards,
Dmitrijs Balabka
WEB-developer

E-Mail: dmitry.balabka@gmail.com
Cell Phone: +371 29671519
Web: http://dmitry.balabka.com/

**Comment by graphific** [comment]
done.

**Comment by torinaki** [comment]
I guess it can be closed.
