### ISSUE TITLE
API to consume data? Widgets to include?

### ISSUE THREAD

**Issue by romanchyla** [samim23/GitXiv#17]
Hi,
Yours is a very powerful idea - of linking software with papers (and indirectly with authors) - some people are discussing it in context of astronomy (or sciences in general).

I didn't spend time going through the code (sorry, I know it is there :)) but I would like to ask some questions:
- would you have any interest in expanding the processing to the whole of arxiv?
- and offer the extracted data for ingestion via API? (I work at ADS, which is also open-source and provides search services for scientists)
- or find a way to connect services

The automated extraction approach is (in _my opinion_) the only one that scales and could work accross fields. And I'm not patient enough until people re-engineer publishing practices :)

**Comment by romanchyla** [comment]
oh, btw, in the heat of excitement i forgot to add a more practical justification (to explain my motivation)

i work for ADS and we are running the same services (only little bit longer ;)) - and ADS search index contains all of arxiv already!

https://ui.adsabs.harvard.edu
https://github.com/adsabs/bumblebee
https://github.com/adsabs/adsabs-dev-api

**Comment by graphific** [comment]
hi @romanchyla I got nothing but respect for ADS, such a great initiative it seems from scanning it quickly! 
It seems to be pretty much focused on astronomy and physics, right?

With GitXiv we imagine a federated model where people from different disciplines can create their own discipiline.gitxiv.com portal, ie astronomy.gitxiv.com. The current version is mainly focused on Computer Science, as thats where I come from and is also Samim's current focus.
For us community is just as important as the virtual infrastructure, so thats one of the reasons why we think this might be the way to go (but as with everything of GitXiv, were totally for discussing this). 

As for your question about expanding the processing to the whole of arxiv: With GitXiv we only posts items when both the code and the article are freely (so no paywall, or other limitations) available. In an ideal world with would be github+arxiv, but can sometimes also be zip files on a university web page (As Stanford's NLP lab tends to do). 
In this way we try to promote real open science, and incentive authors to make their code available together with the article. In all reality: with computer-science as a discipline were making real steps towards this as a new de facto norm, but were not there yet by far. 
If code is not available we might try to reach out to the author of an article, or as we also just started: we organize a [competition](http://gitxiv.com/page/competitions) about [implementing the article](https://github.com/GitXiv/DeepQA) collaboratively with other researchers. 

Roman, maybe you would be up for a short chat one of these days? I would love to hear more about the work of ADS, and how we might cooperate!

ps. you can find my email at my [github user page](https://github.com/graphific)

**Comment by romanchyla** [comment]
cool! I'll send you an email. Thanks for getting back to us

**Comment by romanchyla** [comment]
oh, oh, i'm running wild (then realizing i forgot to answer something :))

yes, ADS is focused on astronomy - there is another project, that focuses on physics (our collaborators: https://inspirehep.net/) - but the two systems are separate and have different design/development philosophies

ADS indexes all of the arxiv and the ADS Classic site (http://adsabs.harvard.edu/) is used by 1M users a month - the bumblebee is the new generation, which we are building right now to replace the aging system; out of the 1M sessions (which is probably ~400K users), 50K are astronomers. these are the core users and ADS breaths for them :) - but non-core users constitute a big part of the audience too

and in astronomy, the github and open-source software is becoming increasingly popular - to certain extend, the two fields are similar (love for arxiv, open source, open science, impatience with the traditional publishing models)
