### ISSUE TITLE
personal library

### ISSUE THREAD

**Issue by graphific** [samim23/GitXiv#19]
from [reddit](https://www.reddit.com/r/MachineLearning/comments/3ew74t/gitxivcom_collaborative_open_computer_science/ctjf4sn):
<i>Also: a way to maybe save each post in a library of some sort for each user?</i>

At your profile page you already have a list of upvoted posts, is this enough?
<img width="404" alt="upvoted" src="https://cloud.githubusercontent.com/assets/10637696/9053675/6c05fac2-3a78-11e5-9c33-1d76890ed419.png">

Or maybe the possibility to create your own personal collection? ie NLP or CV

**Comment by manniche** [comment]
The "upvote post" metaphor is not available inside a opened post. The ability to "star" a post would perhaps be easier understandable? It would also be more pervasive in that the verb would remain unchanged in all contexts (upvoting a post without a context might in some situations seem non-sensible)

**Comment by sotte** [comment]
A 'star' feature would be nice. It's widely understood.

**Comment by iRonJ** [comment]
I ++ this request
