### ISSUE TITLE
Feature request: RSS feed

### ISSUE THREAD

**Issue by jedi00** [samim23/GitXiv#2]
Hi, I came across your site, and it's very worth mentioning. What I want to suggest here is that can you provide rss feed? It's much convenient than newsletter.

**Comment by samim23** [comment]
Hi, RSS feeds are a great idea. 
Do you want this per category or an overall feed? We´ll activate the RSS feeds asap!

**Comment by jedi00** [comment]
For me an overall feed is OK. I can do the category filtering by myself. It would be hard to pre-categorized feeds meeting everybody's requirement.

**Comment by samim23** [comment]
Cool, there u go: http://gitxiv.com/feed.xml

**Comment by graphific** [comment]
todo: no description field yet
