### ISSUE TITLE
HTTPS certificate for gitxiv.com is for a different domain

### ISSUE THREAD

**Issue by ansell** [samim23/GitXiv#21]
The HTTPS certificate for gitxiv.com is actually a wildcard for the domains:

```
*.onmodulus.net
```

This causes Firefox to give a warning page, which may prevent people clicking through to the site unless they are familiar with the meaning of the message.

**Comment by samim23** [comment]
Indeed, SSL/HTTPS are currently not addressed, http only. Same goes for www.gitxiv.com, which does not work. We will look into solving this.

**Comment by ansell** [comment]
Until this is fixed, it may be useful to change the URL on the README.md file to be http://gitxiv.com instead of https://gitxiv.com, as that is how I browsed to it and others may do the same.
