### ISSUE TITLE
Set up a bioinformatics version of gitxiv

### ISSUE THREAD

**Issue by ctb** [samim23/GitXiv#25]
Please watch this issue and/or comment if you are interested in working together on a bioinformatics verison!

Please add in links etc to interesting and relevant things below.

Things to discuss: 
- how would this be different from the bioinformatics category already? http://gitxiv.com/category/bioinformatics
- what unique/odd things would there be about a bioinformatics gitxiv? links to biorxiv?

**Comment by sahilseth** [comment]
Just throwing out some ideas, I think the approach could be quite different. The categories could be:

Focussing on data:

- Aligners
- Variant Callers
- CNV callers
- Variant annotators
- Workflow tools
...

For several downstream methods, there might be, there might be cross listing with gitXiv (NMF, cluster plus pkg etc..).

Taking cues from [omictools.com](omictools.com), except this would contains articles which are freely available and code is on github/bitbucket etc.

Or adding a special tab on gitxiv, which says bioinfo tools, and then list the above categories would could be another option.

**Comment by samim23** [comment]
These are great ideas! We will take it into accountant while designing the next GitXiv iteration. Ideally we get a admin involved with deep domain knowledge for this.

**Comment by NDuma** [comment]
Finding that Bioinformatics is under several categories listed when doing a search:
Computer Science > Learning
https://arxiv.org/abs/1603.06430
Computer Science > Digital Libraries
https://arxiv.org/abs/1607.02974
Computer Science > Data Structures and Algorithms
https://arxiv.org/abs/1703.00667

Quantitative Bio is a Category there:
Mirroring the Taxonomy of Arxiv.org should work yeah?
https://arxiv.org/archive/q-bio

**Comment by NDuma** [comment]
How about Hardware!
That's what brought me in here!
- instead I filed 2 other issues & realized BioInfo is nearly the same Issue!
https://arxiv.org/abs/1704.04760

Update the Taxonomy!
