### ISSUE TITLE
Reproducible environments via Binder?

### ISSUE THREAD

**Issue by freeman-lab** [samim23/GitXiv#27]
Really cool project! Coming from neuroscience, which is largely wedded to the traditional journal model, this is so clearly the way forward, and provides an awesome example.

A key part of sharing code is making it reproducible and executable, and we've been working on an open-source project for doing exactly this, straight from GitHub, called Binder.

http://mybinder.org/

It literally adds a "run this in a virtual machine button" to a repo, an example with one is here:

https://github.com/binder-project/example-requirements

It might be cool to integrate with GitXiv! Even something simple like adding the direct launch button / link if a Binder has been made for a given project's repo?

If this might be of interest, I'd be happy to take a stab at a PR!

cc @andrewosh

**Comment by samim23** [comment]
Hi there, would be good to explore this further face2face. You use skype?

**Comment by freeman-lab** [comment]
@samim23 sounds great! could do tomorrow around 2pm? you can email me at the.freeman.lab@gmail.com to confirm
