### ISSUE TITLE
Book "signal processing using python(ipython notebooks)"

### ISSUE THREAD

**Issue by rajendraranabhat** [samim23/GitXiv#28]
Please add this in book section:

https://github.com/unpingco/Python-for-Signal-Processing

**Comment by graphific** [comment]
@rajendraranabhat you do know you can do it yourself? :)

**Comment by graphific** [comment]
ok then: http://www.gitxiv.com/posts/tXgfq5T7BjRncLRzn/signal-processing-using-python-ibook
