### ISSUE TITLE
 Follow-Feature / Interests

### ISSUE THREAD

**Issue by VolutionLabs** [samim23/GitXiv#31]
It might be nice to further develop the "follow"-feature. 
If I am interested in the further evolvement of a project/article(/field), I have to "subscribe to comment thread" now and then get notifications, when there are updates. It would be nice if there was a section, where I could see, what I am following.

**Comment by samim23** [comment]
A fantastic idea. The follower model would lend it self nicely and help cut down on noise. 
A few observations: 

1) the current frequency of research being posted on GitXiv is "low", compared with other "follower" model sites, like twitter. This could lead to "segregated, dead streams".

2) The development of such a feature is time intensive. Making it scaleable and flexible tricky.

**Comment by VolutionLabs** [comment]
some ideas:

to increase participation 
	
to let people dare to comment 
--> high level more joyful

to further define gitvix profile and tendencies. Closeness to arxiv:(academic scientific) or (tech scientific):more open to new shapes of effective collaboration.

widen framework:
“It elevates the academic discourse and lets the public participate and learn. “ 
“collaborative open computer science projects” /filters e.g. degrees of complexity level 

not just papers?
by opening up frameset (arxiv+git+()) to blog-entries/youtube+git — there are so many high level projects around. 

e.g *gem* entries/nodes/pages that combine e.g. a youtube lecture with github repositories  ipython notebooks, blog entries, so that it provides an executable entity and also has information about related contexts/embeddings. (if subelements were also tagable, there could be wider interfaces to interconnected elements)

meaning:
abstraction of / combination of special aspects/concepts/infos/nodes/

sorting: 
namespaces “Categories” (in accordance with basic taxonomy (state of the arts ICT?(we are already very close to other fields!(->meta-leveled concerns(->STEM, etc.))) (or which (sub)sector))) (->”is (dbp):discipline of” namespaces/semantics/taxonomy/ontology engineering(->(COLLABORATIVE) KNOWLEDGE GRAPH (with editable nodes/links))*)


— “open computer science (cocs)” - it is hard to find a clear description of that concept out there.

“Open Computer Science is an open access, peer-reviewed journal. The journal publishes research results in the following fields:
	•	algorithms and complexity theory
	•	artificial intelligence
	•	bioinformatics
	•	networking and security systems
	•	programming languages
	•	system and software engineering
	•	theoretical foundations of computer science”
[http://www.degruyter.com/view/j/comp]

or ist it directly connected to https://github.com/open-source-society/computer-science

who suggest those categories
	•	Introduction to Computer Science
	•	Math (Mathematical Thinking)
	•	Program Design
	•	Math (Discrete Math)
	•	Algorithms
	•	Programming Paradigms
	•	Software Testing
	•	Math (Calculus)
	•	Software Architecture
	•	Theory
	•	Software Engineering
	•	Math (Probability)
	•	Computer Architecture
	•	Operating Systems
	•	Computer Networks
	•	Databases
	•	Cloud Computing
	•	Math (Linear Algebra)
	•	Cryptography
	•	Security
	•	Compilers
	•	Parallel Computing
	•	UX Design
	•	Computer Graphics
	•	Artificial Intelligence
	•	Machine Learning
	•	Natural Language Processing
	•	Big Data
	•	Data Mining
	•	Internet of Things
	•	Specializations



… as early as we start to sort those and create taxonomies, we are already into creating a knowledge graph…

if there is a special task force that is working on the namespace/ontology, I would love to join!
