### ISSUE TITLE
Recurrent Neural Network Grammars

### ISSUE THREAD

**Issue by danielhers** [samim23/GitXiv#38]
http://arxiv.org/pdf/1602.07776v1.pdf

**Comment by graphific** [comment]
@danielhers is the code also available somewhere?

**Comment by danielhers** [comment]
Not that I know if. I thought creating an issue here expresses a request
for it to be made available.

**Comment by graphific** [comment]
yes it does I guess :) Let's see if someone picks it up :+1:
