### ISSUE TITLE
Convert article to Kindle .mobi

### ISSUE THREAD

**Issue by ferrouswheel** [samim23/GitXiv#43]
This might be little outside the original aim of GitXiv, but I really love the way it already augments arxiv.org.

I'm about to go travelling and was exploring the best way to read pdf articles on my Kindle, because I hate printing them out and wasting paper. To that end I came across this perl script: http://knanagnostopoulos.blogspot.co.nz/2013/03/from-arxiv-directly-to-my-kindle_15.html

There were also a number of other options out there.

I'm tempted to try and go through the hoops to create this anyhow, I could either provide an API to convert, or directly include it in gitxiv? The question though, is would this be useful to anyone?

**Comment by Spotlight0xff** [comment]
I'm also interested in this!
Is there any progress?

I have a script for myself, see https://github.com/Spotlight0xff/scripts/blob/master/arxiv_kindle.py
Would love to have this included/used within gitxiv :)
Btw, the python script is based on this notebook: https://gist.github.com/bshillingford/6259986edca707ca58dd

**Comment by ferrouswheel** [comment]
I've not yet attempted this. Please feel free to give it a go :-)

**Comment by stared** [comment]
I tried many things, and by far the best approach is http://dontprint.net/ (a Chrome and Firefox extensions), which actually works (regexes to change LaTeX code rarely work). I recommend it to the point I think it would be good to link to it (it will save many trees).

I've discovered it thanks to this discussion: [Reading arXiv preprints on an e-reader? - r/MachineLearning](https://www.reddit.com/r/MachineLearning/comments/5xtnl4/d_reading_arxiv_preprints_on_an_ereader/).

**Comment by Spotlight0xff** [comment]
As mentioned in the reddit thread as well, k2pdfopt works reasonable well (and dontprint is based on that tool as per thread). So maybe rather link to k2pdfopt to have a more universal solution? We never know how long the service (no offense to the owner of dontprint!) will persist, while K2pdfopt is well established.

**Comment by stared** [comment]
@Spotlight0xff In this context Dontprint makes much more sense, for a end-user solution, as it downloads, converts and emails paper, all within browser. In any case, it is open source [robamler/dontprint](https://github.com/robamler/dontprint/) and to make it clear, I have not relationship with this project or its author.

Of course, it may last long or not. But as long as it is useful, why not linking to it?

Linking to k2pdfopt near arXiv link makes little sense - it's hardly plug&play, and requires quite a few steps to actually accomplish task. So, it won't save trees.
