### ISSUE TITLE
API for developers?

### ISSUE THREAD

**Issue by vsoch** [samim23/GitXiv#45]
This issue has likely already been brought up, but is there any plan to make an API? it would be great to have programmatic access to the data, versus standard web scraping of things :)

**Comment by vsoch** [comment]
Is that a no? lol.

**Comment by samim23** [comment]
Please refer to the following notice on this repos readme:

Notice: I no longer maintain GitXiv (code&server). This Repo is just here or legacy reasons. Please address your Issues else where.
