### ISSUE TITLE
The about page is broken!

### ISSUE THREAD

**Issue by guillaume-chevalier** [samim23/GitXiv#66]
![](https://image.ibb.co/knmuZ5/about.png)

And you should fix other things, some other pages takes 10 seconds to load or don't load at all.

**Comment by samim23** [comment]
I no longer maintain GitXiv. This Repo is just here or legacy reasons. Please address your concerns towards the new owners.

**Comment by zhiyue** [comment]
@samim23 
Who is the new new owner?
