### ISSUE TITLE
Gitxiv Competition Idea: Deep Q&A Neural Conversation Model

### ISSUE THREAD

**Issue by samim23** [samim23/GitXiv#8]
Name: Deep Q&A Neural Conversation Model (Google)  
Paper: http://arxiv.org/pdf/1506.05869v1.pdf

**Comment by GitXiv** [comment]
check it out: 
* http://gitxiv.com/page/competitions
* https://github.com/GitXiv/DeepQA
* https://github.com/GitXiv/DeepQA/wiki/Getting-started-with-DeepQA

**Comment by graphific** [comment]
implemented, and working on it; so closing for now.

**Comment by jtoy** [comment]
where is it on github?
